server:
  port: 8087
spring:
  datasource:
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5888/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

student:
  balance: 5
  list:
    - Hello
    - Goodbye
    - Goodmorning